# Generated by Django 4.1.2 on 2022-10-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Category <built-in function id>', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='Note <built-in function id>', help_text='Choose note title', max_length=50, verbose_name='Title'),
        ),
    ]
