# Generated by Django 4.1.2 on 2022-10-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Category', help_text='Choose category name', max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an optional image', null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='Note', help_text='Choose note title', max_length=20, verbose_name='Title'),
        ),
    ]
