# Generated by Django 4.1.2 on 2022-10-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_category_name_alter_notes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Category <built-in function id>', max_length=50, null=True, verbose_name='Name'),
        ),
    ]
