# Generated by Django 4.1.2 on 2022-10-26 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0005_alter_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.ForeignKey(blank=True, default='Category <django.db.models.query_utils.DeferredAttribute object at 0x0000019ACA9CDA20>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.category'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(help_text='Choose note title', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(auto_created=True, default='<django.db.models.query_utils.DeferredAttribute object at 0x0000019ACA9A7520>', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
