# Generated by Django 4.1.2 on 2022-10-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_notes_category_alter_notes_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.ForeignKey(blank=True, default='Category <django.db.models.query_utils.DeferredAttribute object at 0x000001ABA7A3E530>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.category'),
        ),
    ]
