# Generated by Django 4.1.2 on 2022-10-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_notes_user_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.ForeignKey(blank=True, default='Category <django.db.models.query_utils.DeferredAttribute object at 0x000001DBC34EE530>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.category'),
        ),
    ]
