# Generated by Django 4.1.2 on 2022-10-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_category_name_alter_notes_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an optional image', null=True, upload_to='', verbose_name='Image'),
        ),
    ]
