# Generated by Django 4.1.2 on 2022-10-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_notes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='Note <built-in function id>', help_text='Choose note title', max_length=20, verbose_name='Title'),
        ),
    ]
