# Generated by Django 4.1.2 on 2022-10-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_notes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Category', help_text='Choose category name', max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='Note', help_text='Choose note title', max_length=20, verbose_name='Title'),
        ),
    ]
