# Generated by Django 4.1.2 on 2022-10-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
